services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8001:8000"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8002:8000"
      - "50051:50051"
    depends_on:
      - redis

  orders-service:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "8000:8000"
    depends_on:
      - inventory-service
      - rabbitmq

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq
  
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - inventory-service

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus